#!/usr/bin/env python3
"""
ARC Protocol - Changelog Generator
Generates CHANGELOG.md from phase summaries
"""
import os
import glob
from datetime import datetime

ARC_DIR = ".arc"
PLANNING_DIR = os.path.join(ARC_DIR, "planning")
ARCHIVE_DIR = os.path.join(ARC_DIR, "archive")

def extract_summary(file_path):
    """Extract key information from phase summary"""
    if not os.path.exists(file_path):
        return None
    
    with open(file_path, 'r') as f:
        content = f.read()
    
    # Extract phase name and completion date
    lines = content.split('\n')
    phase_name = lines[0].replace('#', '').strip() if lines else "Unknown Phase"
    
    summary = {
        'phase': phase_name,
        'completed': 'Unknown',
        'added': [],
        'changed': [],
        'fixed': []
    }
    
    current_section = None
    for line in lines:
        if '## Completed' in line:
            # Next line should be date
            continue
        elif line.startswith('## What Was Built'):
            current_section = 'added'
        elif line.startswith('## Key Decisions'):
            current_section = 'changed'
        elif line.startswith('## Known Issues'):
            current_section = 'fixed'
        elif line.startswith('-') and current_section:
            summary[current_section].append(line.strip('- ').strip())
    
    return summary

def generate_changelog():
    """Generate CHANGELOG.md from all phase summaries"""
    print("📝 Generating CHANGELOG.md from phase summaries...")
    
    # Find all phase summaries
    summaries = []
    for summary_file in sorted(glob.glob(os.path.join(PLANNING_DIR, "*-SUMMARY.md"))):
        s = extract_summary(summary_file)
        if s:
            summaries.append(s)
    
    for summary_file in sorted(glob.glob(os.path.join(ARCHIVE_DIR, "*-SUMMARY.md"))):
        s = extract_summary(summary_file)
        if s:
            summaries.append(s)
    
    if not summaries:
        print("⚠️  No phase summaries found. Complete some phases first!")
        return
    
    # Generate changelog
    changelog = f"""# Changelog

All notable changes to this project are documented here.

Generated by ARC Protocol on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

"""
    
    for summary in reversed(summaries):  # Most recent first
        changelog += f"## {summary['phase']}\n\n"
        
        if summary['added']:
            changelog += "### ✨ Added\n"
            for item in summary['added']:
                changelog += f"- {item}\n"
            changelog += "\n"
        
        if summary['changed']:
            changelog += "### 🔧 Changed\n"
            for item in summary['changed']:
                changelog += f"- {item}\n"
            changelog += "\n"
        
        if summary['fixed']:
            changelog += "### 🐛 Fixed\n"
            for item in summary['fixed']:
                changelog += f"- {item}\n"
            changelog += "\n"
        
        changelog += "---\n\n"
    
    # Write to file
    with open("CHANGELOG.md", 'w') as f:
        f.write(changelog)
    
    print(f"✅ CHANGELOG.md generated with {len(summaries)} phases!")
    print(f"📄 Location: ./CHANGELOG.md")

if __name__ == "__main__":
    generate_changelog()
