import os
import re
import sys

def get_mermaid_topology(root_dir):
    nodes = []
    edges = []
    
    # Define color classes
    classes = """
    classDef frontend fill:#00c4cc,stroke:#333,stroke-width:2px;
    classDef api fill:#f96,stroke:#333,stroke-width:2px;
    classDef backend fill:#69f,stroke:#333,stroke-width:2px;
    classDef db fill:#8b5cf6,stroke:#333,stroke-width:2px;
    """

    # Scan for major directories
    subgraphs = {}
    for d in os.listdir(root_dir):
        if d.startswith(".") or d == "node_modules" or d == "venv":
            continue
        if os.path.isdir(os.path.join(root_dir, d)):
            subgraphs[d] = []
            # Scan files in this subdir
            for root, dirs, files in os.walk(os.path.join(root_dir, d)):
                if "node_modules" in root: continue
                for f in files:
                    if f.endswith((".ts", ".tsx", ".py", ".js", ".go")):
                        subgraphs[d].append(f)

    # Generate Mermaid
    mermaid = ["graph TD", classes]
    
    for sg, files in subgraphs.items():
        mermaid.append(f"    subgraph \"{sg.upper()}\"")
        for f in files[:5]: # Cap at 5 for clarity
            node_id = f.replace(".", "_")
            mermaid.append(f"        {node_id}[{f}]")
            # Logic for styling
            if sg == "frontend": mermaid.append(f"        class {node_id} frontend")
            elif sg == "backend" or sg == "src": mermaid.append(f"        class {node_id} backend")
            elif sg == "api": mermaid.append(f"        class {node_id} api")
        mermaid.append("    end")

    # Trace imports for basic edges
    # This is expensive, so we just do a few key files for demonstration
    # In v2.0 real version we would parse all files
    
    return "\n".join(mermaid)

def main():
    root = "."
    topology = get_mermaid_topology(root)
    
    output_path = "CODEBASE_MAP.md"
    with open(output_path, "w") as f:
        f.write("# 🗺️ ARC Ghost Navigator: Visual Topology\n\n")
        f.write("```mermaid\n")
        f.write(topology)
        f.write("\n```\n")
        f.write("\n\n*Generated by ARC v2.1 Parallel Engine.*")

    print(f"[✓] Visual Topology generated to {output_path}")

if __name__ == "__main__":
    main()
